yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views


app_name = 'posts'

urlpatterns = [
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
    path('', views.index, name='index'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

from core.models import CreatedModel

User = get_user_model()
COUNT_SYMBOL = 15


class Post(CreatedModel):
    text = models.TextField()
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        'Group',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ('-pub_date',)

    def __str__(self):
        return str(self.text)[:COUNT_SYMBOL]


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Comment(CreatedModel):
    text = models.TextField()
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='comments',
                               )
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments',
                             )

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.text[:COUNT_SYMBOL]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=('user', 'author'),
                name="unique followers"),
            models.CheckConstraint(
                check=~models.Q(user=models.F('author')),
                name='do not selffollow'),
        ]

yatube/posts/forms.py
from django.core.exceptions import ValidationError
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')

    def clean_text(self):
        data = self.cleaned_data['text']
        if data == '':
            raise ValidationError('напишите текст поста')
        return data


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from .forms import PostForm, CommentForm
from .models import Group, Post, User, Follow


COUNT_POST = 10


def page(request, post_list):
    paginator = Paginator(post_list, COUNT_POST)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return page_obj


def index(request):
    posts = Post.objects.select_related('group').all()[:COUNT_POST]
    post_list = Post.objects.all()
    page_obj = page(request, post_list)
    context = {
        'posts': posts,
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()[:COUNT_POST]
    post_list = group.posts.all()
    page_obj = page(request, post_list)
    title = ''
    context = {
        'title': title,
        'group': group,
        'posts': posts,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    post_list = author.posts.all()
    page_obj = page(request, post_list)
    context = {
        'author': author,
        'num_post_list': post_list.count(),
        'page_obj': page_obj,
        'following': False,
    }
    if request.user.is_authenticated:
        if Follow.objects.filter(user=request.user, author=author).exists():
            context['following'] = True
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    posts = Post.objects.filter(author__exact=post.author).count()
    posts_count = posts
    form = CommentForm()
    comments = post.comments.all().select_related('author')
    context = {
        'post': post,
        'posts_count': posts_count,
        'form': form,
        'comments': comments,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required(login_url="user:login")
def post_create(request):
    form = PostForm()
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('posts:profile', username=request.user.username)
        context = {'form': form}
    context = {'form': form}
    return render(request, 'posts/create_post.html', context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if request.user != post.author:
        return redirect('posts:post_detail', post_id)
    context = {
        'form': form,
        'post': post,
        'is_edit': True,
    }
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post.id)
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    post_list = Post.objects.filter(author__following__user=request.user)
    page_obj = page(request, post_list)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if request.user != author:
        Follow.objects.get_or_create(
            user=request.user,
            author=author
        )
    return redirect('posts:follow_index')


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user, author=author).delete()
    return redirect('posts:follow_index')

yatube/templates/posts/add_comment.html
{% load user_filters %}

{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}      
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}

{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
      <p>
        {{ comment.text }}
      </p>
    </div>
  </div>
{% endfor %}

yatube/templates/posts/create_post.html
{% extends 'base.html' %}

{% block title %}
  {% if is_edit %} Редактировать пост {% else %} Новый пост {% endif %}
{% endblock %}

{% block content %}
  {% load user_filters %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            {% if is_edit %} Редактировать пост {% else %} Новый пост {% endif %}
          </div>
          <div class="card-body">
            {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endif %}
            <form method="post" enctype="multipart/form-data">
              {% csrf_token %}
              {% for field in form %}
                <div class="form-group row my-3 p-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                    {% if field.field.required %}
                      <span class="required text-danger">*</span>
                    {% endif %}
                  </label>
                  {{ field|addclass:'form-control' }}
                  {% if field.help_text %}
                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                      {{ field.help_text|safe }}
                    </small>
                  {% endif %}
                </div>
              {% endfor %}
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %} Сохранить {% else %} Добавить {% endif %}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  Подписки
{% endblock %}
{% block content %}
{% include 'posts/includes/switcher.html' %}
  {% for post in page_obj %} <!-- был posts-->
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }}
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>{{ post.text }}</p>    
    {% if post.group %}
    <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  Записи сообщества {{ group.title }}
{% endblock %}
{% block content %}
  <h1> {{ group.title }} </h1>
  <p> {{ group.description }}</p>
  {% for post in page_obj %} <!--тут был posts-->
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }}
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>{{ post.text }}</p>    
    <a href="">все записи группы</a>
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load cache %}
{% block title %}
  Последние обновления на сайте
{% endblock %}
{% block content %}
{% cache 20 index_page %}
{% include 'posts/includes/switcher.html' %}
  {% for post in page_obj %} <!-- был posts-->
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }}
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>{{ post.text }}</p>    
    {% if post.group %}
    <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endcache %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  Пост {{ post.text|truncatechars:30 }}
{% endblock %}
{% block content %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
        <li>
        {% if post.group %}
            Группа: {{ post.group.slug }}
            <a href="{% url 'posts:group_list' post.group.slug %}">
            все записи группы
            </a>
        {% endif %}
        </li>
          <li class="list-group-item">
            Автор: {{ post.author.get_full_name }}
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            Всего постов автора:<span >{{ posts_count }}</span>
          </li>
          <li class="list-group-item">
            <a href="{% url 'posts:profile' post.author.username %}">
              все посты пользователя
            </a>
          </li>
        </ul>
      </aside>
      <article class="col-12 col-md-9">
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>
          {{ post.text }}
        </p>
      </article>
  </div>
{% include 'posts/add_comment.html' %}
{%endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  Профайл пользователя {{ author }}
{% endblock %}
{% block content %}
  <div class="container py-5">    
    <div class="mb-5">    
    <h1>Все посты пользователя {{ author }} </h1>
    <h3>Всего постов: {{ num_post_list }} </h3> 
    {% for post in page_obj %} <!-- был posts-->
    <article>
      <ul>
        <li>
            Автор: {{ post.author.get_full_name }}
        </li>    
        <li>  
          <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a> <!-- добавил урл целиком  -->
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
    {% if following %}
    <a
      class="btn btn-lg btn-light"
      href="{% url 'posts:profile_unfollow' author.username %}" role="button"
    >
      Отписаться
    </a>
    {% else %}
      <a
        class="btn btn-lg btn-primary"
        href="{% url 'posts:profile_follow' author.username %}" role="button"
      >
        Подписаться
      </a>
    {% endif %}
    </div>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>
        {{ post.text }}
      </p>
      <a href="{%url 'posts:post_detail' post.id%}">подробная информация </a>
    </article>            
    <hr>
    <!-- Остальные посты. после последнего нет черты -->
    <!-- Здесь подключён паджинатор -->  
    {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}